1.the first try of jax（简单的检测）

In [1]:
pip install --upgrade "jax[cuda12.2]" 

Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Note: you may need to restart the kernel to use updated packages.


In [2]:
!pip install numpy torch matplotlib

Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple


In [3]:
!pip install --upgrade jax

Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple


In [4]:
 
import jax.numpy as np
 
from jax import random
 
import time
 
x = random.uniform(random.PRNGKey(0), [5000, 5000])
 
st=time.time()
 
try:
 
    y=np.matmul(x, x)
 
except Exception:
 
    print("erro")
 
print(time.time()-st)
 
print(y)

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.


0.04753851890563965
[[1261.065  1244.5798 1237.2274 ... 1264.721  1246.037  1260.5391]
 [1256.1001 1239.737  1237.5563 ... 1257.1332 1243.5852 1243.5978]
 [1261.2687 1239.5004 1250.6694 ... 1259.8386 1250.6824 1248.5712]
 ...
 [1265.9806 1230.9076 1244.496  ... 1264.2375 1241.5996 1244.9275]
 [1262.9973 1253.9614 1256.2426 ... 1266.3485 1255.1581 1274.1865]
 [1273.3525 1252.4922 1261.0494 ... 1273.2395 1272.8289 1267.7482]]


In [5]:
import numpy as np
 
import time
 
x = np.random.random([5000, 5000]).astype(np.float32)
 
try:
 
    st=time.time()
 
    y=np.matmul(x, x)
 
except Exception:
 
    print("erro")
 
print(time.time()-st)
 
print(y)

0.29421353340148926
[[1266.0521 1244.3492 1250.473  ... 1254.7515 1255.2498 1273.1646]
 [1254.2166 1234.985  1250.4999 ... 1253.28   1242.5857 1270.5966]
 [1256.092  1233.3672 1254.7457 ... 1243.8411 1245.7468 1266.3936]
 ...
 [1251.9117 1240.8333 1246.5258 ... 1241.3053 1236.0017 1260.5897]
 [1264.1781 1246.8868 1253.0725 ... 1256.7112 1245.0349 1281.681 ]
 [1238.217  1223.2812 1241.6333 ... 1230.8494 1244.1259 1266.9929]]
