1.the first try of jax（简单的检测）

In [40]:
pip install --upgrade "jax[cuda12.2]" 

/usr/lib/python3.11/pty.py:89: RuntimeWarning: os.fork() was called. os.fork() is incompatible with multithreaded code, and JAX is multithreaded, so this will likely lead to a deadlock.
  pid, fd = os.forkpty()


Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Note: you may need to restart the kernel to use updated packages.


In [41]:
!pip install numpy torch matplotlib

Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple


In [42]:
!pip install --upgrade jax

Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple


In [49]:
 
import jax.numpy as np
 
from jax import random
 
import time
 
x = random.uniform(random.PRNGKey(0), [5000, 5000])
 
st=time.time()
 
try:
 
    y=np.matmul(x, x)
 
except Exception:
 
    print("erro")
 
print(time.time()-st)
 
print(y)

0.061272621154785156
[[1261.065  1244.5798 1237.2274 ... 1264.721  1246.037  1260.5391]
 [1256.1001 1239.737  1237.5563 ... 1257.1332 1243.5852 1243.5978]
 [1261.2687 1239.5004 1250.6694 ... 1259.8386 1250.6824 1248.5712]
 ...
 [1265.9806 1230.9076 1244.496  ... 1264.2375 1241.5996 1244.9275]
 [1262.9973 1253.9614 1256.2426 ... 1266.3485 1255.1581 1274.1865]
 [1273.3525 1252.4922 1261.0494 ... 1273.2395 1272.8289 1267.7482]]


In [50]:
import numpy as np
 
import time
 
x = np.random.random([5000, 5000]).astype(np.float32)
 
try:
 
    st=time.time()
 
    y=np.matmul(x, x)
 
except Exception:
 
    print("erro")
 
print(time.time()-st)
 
print(y)

0.2953653335571289
[[1278.8392 1272.5056 1281.6112 ... 1280.5994 1284.577  1277.9277]
 [1250.8505 1267.1465 1278.6779 ... 1270.0315 1283.1343 1275.9945]
 [1255.3877 1256.9326 1277.9678 ... 1251.7395 1271.203  1263.7208]
 ...
 [1251.0992 1251.8818 1271.9391 ... 1258.3875 1258.0483 1250.3754]
 [1246.1051 1256.3242 1261.0276 ... 1259.925  1274.0005 1261.2765]
 [1224.8632 1225.1902 1232.2507 ... 1237.4371 1234.2573 1230.1326]]
